version: '3.8'

services:
  composer:
    container_name: if-alumni-composer
    image: composer:latest
    command: update
    volumes:
      - ./wordpress:/app

  mysql:
    container_name: if-alumni-db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    volumes:
      - ./mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   depends_on:
  #     - mysql
  #   environment:
  #     PMA_HOST: mysql
  #     PMA_PORT: 3306
  #     PMA_ARBITRARY: 1
  #   restart: always
  #   ports:
  #     - 8080:80 

  wordpress:
    container_name: if-alumni-wp
    depends_on:
      - mysql
      - composer
    build: .
    image: panithi228/if-alumni-wp:latest
    ports:
      - 8041:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    # volumes:
    #   - ./wordpress:/var/www/html